package recommendation;

import utilities.Helper;
import fileio.ActionInputData;
import fileio.UserInputData;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Provides the favorite recommendation method
 */
public class FavoriteRec {
    private final List<UserInputData> users;

    public FavoriteRec(final List<UserInputData> users) {
        this.users = users;
    }

    /**
     * Recommends the video that was the most added in the
     * favorite list of the uses
     * @param action type of action
     * @throws IOException in case of exceptions to reading / writing
     */
    public void gerFavoriteRec(final ActionInputData action) throws IOException {
        UserInputData user1 = Helper.findUser(users, action);
        assert user1 != null;
        if (user1.getSubscriptionType().equals("BASIC")) {
            Helper.writeToOutput(action, "FavoriteRecommendation cannot be applied!");
            return;
        }
        HashMap<String, Integer> favoriteVideos = new HashMap<>();

        for (UserInputData user : users) {
            ArrayList<String> favorites = user.getFavoriteMovies();
            for (String favorite : favorites) {
                    favoriteVideos.merge(favorite, 1, Integer::sum);
            }
        }
        HashMap<String, Integer> favoriteVideosSorted = new LinkedHashMap<>();
        // the next 5 lines of code are auto-generated by the INTELIJJ ide
        // no idea why it recommends me this but it is 0.1 seconds faster than my
        // sorting method which involves streams
        List<Map.Entry<String, Integer>> toSort = new ArrayList<>(favoriteVideos.entrySet());
        toSort.sort(Map.Entry.comparingByValue(Comparator.reverseOrder()));
        for (Map.Entry<String, Integer> x : toSort) {
            favoriteVideosSorted.put(x.getKey(), x.getValue());
        }
        var favoriteVideosSortedList = new ArrayList<>(favoriteVideosSorted.keySet());

        Map<String, Integer> history = user1.getHistory();
        for (String favorite: favoriteVideosSortedList) {
            if (!history.containsKey(favorite)) {
                Helper.writeToOutput(action, "FavoriteRecommendation result: " + favorite);
                return;
            }
        }
        Helper.writeToOutput(action, "FavoriteRecommendation cannot be applied!");
    }
}
